import type { User, Team, Task, Comment, Activity, CalendarEvent, DashboardStats } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@company.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "admin",
    department: "Engineering",
    joinDate: "2023-01-15",
    status: "active",
    skills: ["React", "TypeScript", "Leadership"],
    phone: "+1-555-0123",
    location: "San Francisco, CA",
  },
  {
    id: "2",
    name: "Sarah Wilson",
    email: "sarah@company.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "manager",
    department: "Design",
    joinDate: "2023-02-20",
    status: "active",
    skills: ["UI/UX", "Design", "Project Management"],
    phone: "+1-555-0124",
    location: "New York, NY",
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike@company.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "member",
    department: "Engineering",
    joinDate: "2023-03-10",
    status: "active",
    skills: ["Node.js", "Python", "Data Analysis"],
    phone: "+1-555-0125",
    location: "Austin, TX",
  },
  {
    id: "4",
    name: "Emily Chen",
    email: "emily@company.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "member",
    department: "Product",
    joinDate: "2023-04-05",
    status: "active",
    skills: ["Product Management", "Data Analysis", "Communication"],
    phone: "+1-555-0126",
    location: "Seattle, WA",
  },
  {
    id: "5",
    name: "David Brown",
    email: "david@company.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "member",
    department: "Marketing",
    joinDate: "2023-05-12",
    status: "active",
    skills: ["Marketing", "Sales", "Communication"],
    phone: "+1-555-0127",
    location: "Los Angeles, CA",
  },
]

export const mockTeams: Team[] = [
  {
    id: "1",
    name: "Frontend Team",
    description: "Responsible for user interface development and user experience",
    color: "#3B82F6",
    leaderId: "1",
    memberIds: ["1", "2", "3"],
    createdAt: "2023-01-15",
    status: "active",
    department: "Engineering",
    budget: 150000,
    goals: ["Improve user experience", "Implement new features", "Optimize performance"],
  },
  {
    id: "2",
    name: "Design System",
    description: "Maintaining and evolving the company design system",
    color: "#10B981",
    leaderId: "2",
    memberIds: ["2", "4"],
    createdAt: "2023-02-01",
    status: "active",
    department: "Design",
    budget: 100000,
    goals: ["Create consistent design language", "Improve accessibility", "Build component library"],
  },
  {
    id: "3",
    name: "Product Strategy",
    description: "Product planning and market analysis",
    color: "#F59E0B",
    leaderId: "4",
    memberIds: ["4", "5"],
    createdAt: "2023-03-01",
    status: "active",
    department: "Product",
    budget: 120000,
    goals: ["Market research", "Product roadmap", "User feedback analysis"],
  },
]

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Implement user authentication",
    description: "Create login/logout functionality with JWT tokens",
    status: "in-progress",
    priority: "high",
    assigneeId: "1",
    teamId: "1",
    createdBy: "1",
    createdAt: "2024-01-15",
    dueDate: "2024-02-15",
    estimatedHours: 40,
    actualHours: 25,
    tags: ["authentication", "security", "backend"],
    attachments: [],
    progress: 65,
  },
  {
    id: "2",
    title: "Design new dashboard layout",
    description: "Create wireframes and mockups for the new dashboard",
    status: "review",
    priority: "medium",
    assigneeId: "2",
    teamId: "2",
    createdBy: "2",
    createdAt: "2024-01-20",
    dueDate: "2024-02-10",
    estimatedHours: 20,
    actualHours: 18,
    tags: ["design", "ui", "dashboard"],
    attachments: [],
    progress: 90,
  },
  {
    id: "3",
    title: "API performance optimization",
    description: "Optimize database queries and implement caching",
    status: "todo",
    priority: "urgent",
    assigneeId: "3",
    teamId: "1",
    createdBy: "1",
    createdAt: "2024-01-25",
    dueDate: "2024-02-05",
    estimatedHours: 30,
    actualHours: 0,
    tags: ["performance", "backend", "optimization"],
    attachments: [],
    progress: 0,
  },
  {
    id: "4",
    title: "User research interviews",
    description: "Conduct interviews with 10 users to gather feedback",
    status: "done",
    priority: "medium",
    assigneeId: "4",
    teamId: "3",
    createdBy: "4",
    createdAt: "2024-01-10",
    dueDate: "2024-01-30",
    estimatedHours: 25,
    actualHours: 28,
    tags: ["research", "user-feedback", "interviews"],
    attachments: [],
    progress: 100,
  },
]

export const mockComments: Comment[] = [
  {
    id: "1",
    taskId: "1",
    userId: "2",
    content: "Great progress on the authentication! The JWT implementation looks solid.",
    createdAt: "2024-01-20T10:30:00Z",
    mentions: ["1"],
    attachments: [],
  },
  {
    id: "2",
    taskId: "1",
    userId: "1",
    content: "Thanks! I'm working on the refresh token logic now. Should be ready for review by tomorrow.",
    createdAt: "2024-01-20T11:15:00Z",
    mentions: [],
    attachments: [],
  },
  {
    id: "3",
    taskId: "2",
    userId: "4",
    content: "The new dashboard design looks amazing! Love the clean layout and improved navigation.",
    createdAt: "2024-01-22T14:20:00Z",
    mentions: ["2"],
    attachments: [],
  },
]

export const mockActivities: Activity[] = [
  {
    id: "1",
    type: "task_created",
    userId: "1",
    targetId: "1",
    targetType: "task",
    description: 'created task "Implement user authentication"',
    createdAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "2",
    type: "task_updated",
    userId: "1",
    targetId: "1",
    targetType: "task",
    description: 'updated task status to "in-progress"',
    createdAt: "2024-01-16T10:30:00Z",
  },
  {
    id: "3",
    type: "comment_added",
    userId: "2",
    targetId: "1",
    targetType: "task",
    description: 'commented on task "Implement user authentication"',
    createdAt: "2024-01-20T10:30:00Z",
  },
  {
    id: "4",
    type: "task_completed",
    userId: "4",
    targetId: "4",
    targetType: "task",
    description: 'completed task "User research interviews"',
    createdAt: "2024-01-30T16:45:00Z",
  },
]

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "1",
    title: "Sprint Planning",
    description: "Plan tasks for the upcoming sprint",
    startDate: "2024-02-05T09:00:00Z",
    endDate: "2024-02-05T11:00:00Z",
    type: "meeting",
    attendeeIds: ["1", "2", "3"],
    teamId: "1",
    location: "Conference Room A",
    isRecurring: true,
    recurrenceRule: "FREQ=WEEKLY;BYDAY=MO",
  },
  {
    id: "2",
    title: "Design Review",
    description: "Review new dashboard designs",
    startDate: "2024-02-08T14:00:00Z",
    endDate: "2024-02-08T15:30:00Z",
    type: "review",
    attendeeIds: ["2", "4"],
    teamId: "2",
    location: "Design Studio",
    isRecurring: false,
  },
  {
    id: "3",
    title: "API Optimization Deadline",
    description: "Deadline for API performance optimization task",
    startDate: "2024-02-05T23:59:00Z",
    endDate: "2024-02-05T23:59:00Z",
    type: "deadline",
    attendeeIds: ["3"],
    teamId: "1",
    isRecurring: false,
  },
]

export const mockDashboardStats: DashboardStats = {
  totalTeams: 3,
  totalMembers: 5,
  activeTasks: 3,
  completedTasks: 1,
  overdueTasks: 0,
  teamPerformance: [
    {
      teamId: "1",
      teamName: "Frontend Team",
      completionRate: 75,
      activeTasks: 2,
    },
    {
      teamId: "2",
      teamName: "Design System",
      completionRate: 90,
      activeTasks: 1,
    },
    {
      teamId: "3",
      teamName: "Product Strategy",
      completionRate: 100,
      activeTasks: 0,
    },
  ],
  memberPerformance: [
    {
      userId: "1",
      userName: "John Doe",
      completedTasks: 0,
      activeTasks: 1,
      efficiency: 85,
    },
    {
      userId: "2",
      userName: "Sarah Wilson",
      completedTasks: 0,
      activeTasks: 1,
      efficiency: 92,
    },
    {
      userId: "3",
      userName: "Mike Johnson",
      completedTasks: 0,
      activeTasks: 1,
      efficiency: 78,
    },
    {
      userId: "4",
      userName: "Emily Chen",
      completedTasks: 1,
      activeTasks: 0,
      efficiency: 95,
    },
  ],
  tasksByStatus: [
    { status: "todo", count: 1 },
    { status: "in-progress", count: 1 },
    { status: "review", count: 1 },
    { status: "done", count: 1 },
  ],
  tasksByPriority: [
    { priority: "low", count: 0 },
    { priority: "medium", count: 2 },
    { priority: "high", count: 1 },
    { priority: "urgent", count: 1 },
  ],
}
